export const WORK = {
  game_center: {
    key: 'game_center',
    title: 'Game Center',
    description: 'Projeto de e-commerce gamer.',
    image: '/work-miniatures/game-center.webp',
    url: 'https://unique-youtiao-335656.netlify.app/',
    date: '01/01/2023',
    gitHub: 'https://github.com',
  },
  netflix: {
    key: 'netflix',
    title: 'Netflix Clone',
    description: 'Clone da interface do Netflix.',
    image: '/work-miniatures/netflix.webp',
    url: 'https://affectionate-newton-dfe167.netlify.app/',
    date: '01/01/2023',
    gitHub: 'https://github.com',
  },
  pokegame: {
    key: 'pokegame',
    title: 'PokeGame',
    description: 'Jogo simples que simula uma batalha pokemon.',
    image: '/work-miniatures/pokegame.webp',
    url: 'https://sad-shirley-ac6d59.netlify.app/',
    date: '01/01/2023',
    gitHub: 'https://github.com',
  },
  todo: {
    key: 'todo',
    title: 'Todo App',
    description: 'Aplicativo de lista de tarefas.',
    image: '/work-miniatures/todo.webp',
    url: 'https://bright-cheesecake-3ac5a9.netlify.app/',
    date: '01/01/2023',
    gitHub: 'https://github.com',
  },
  grafo: {
    key: 'grafo',
    title: 'Grafo',
    description: 'Aplicativo para visualização de grafos.',
    image: '/work-miniatures/grafo.webp',
    url: 'https://graph-d3.netlify.app/',
    date: '01/01/2023',
    gitHub: 'https://github.com',
  },
  mapa: {
    key: 'mapa',
    title: 'Mapa de Calor',
    description:
      'Aplicativo de mapa de calor de empresas de ramos específicos.',
    image: '/work-miniatures/heat-map.webp',
    url: '#',
    date: '01/01/2023',
    gitHub: 'https://github.com',
  },
};
